import { Method } from "./method";

const INDENT = "  ";

export function toClassString(name: string, methods: Method[]): string {
  return `// This file is auto-generated by bindgen. DO NOT EDIT.
import { Id, invoke, invokeStatic } from "./kritajs";

export class ${name} {
  private static readonly __className__ = "${name}";

  private constructor(
    private readonly __id__: Id,
  ) { }

${methods.map(m => `${INDENT}${m.toString()}`).join("\n\n")}
}
`;
}
